version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9299:9200
      - 9399:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elastic:9200/
    ports:
      - 8008:5601
  python:
    build: .
    command:
      ['tail', '-f', '/dev/null'] 

volumes:
  elasticsearch_data:

